export const queries=[
['Pricing summary','lineitem only; group by return flag and line status. Partial aggregates → hash exchange → final aggregates → range exchange and sort.','Use Q1 to separate aggregation distribution from final output ordering. No join is needed.'],
['Minimum-cost supplier','part, partsupp, supplier, nation and region; correlated minimum supply cost becomes a grouped branch joined back to candidates.','The normal capture mixes broadcast and sort-merge joins. Correlated SQL does not imply an RPC or nested query per input row.'],
['Shipping-priority revenue','customer → orders on customer key; orders → lineitem on order key; revenue group and top 10.','With threshold −1, watch the intermediate result change distribution from customer key to order key.'],
['Order-priority checking','orders filtered by date; EXISTS over late lineitems becomes a left-semi join; count per priority.','A semi-join checks membership; it does not multiply an order by every matching lineitem.'],
['Local supplier revenue','region → nation → supplier/customer → orders → lineitem, including supplier/customer nation constraints; group revenue by nation.','Follow all equality keys and residual constraints, not just the number of tables.'],
['Forecast revenue change','lineitem filter on date, discount and quantity; sum extendedprice × discount.','No join, no group keys. Partial aggregation plus SinglePartition exchange yields a single final aggregate.'],
['Volume shipping','supplier and customer nations joined through lineitem and orders; group by supplier nation, customer nation and year.','Two nation roles are distinct scan branches; aliases are not extra physical databases.'],
['National market share','part, lineitem, supplier, orders, customer, nation roles and region; conditional revenue numerator / denominator per year.','CASE expressions feed aggregate state. A columnar pipeline still evaluates SQL null and decimal semantics.'],
['Product-type profit','part filter → lineitem → supplier → partsupp → orders → nation; composite part/supplier equality; yearly national profit.','The threshold −1 example has five sort-merge joins; key changes, not table count alone, explain its many exchanges.'],
['Returned-item revenue','customer, orders, returned lineitems and nation; grouped customer revenue with top 20.','Top-N is not a full global sort of all output rows; inspect TakeOrderedAndProject.'],
['Important stock','partsupp, supplier and nation; per-part stock value compared with a fraction of total stock value.','The scalar aggregate subquery is a separate branch; reused exchange nodes can share work.'],
['Shipping modes','orders ⋈ lineitem; date/order constraints and conditional counts by ship mode.','Join-key equality aligns rows; residual date predicates and CASE conditions have different roles.'],
['Customer distribution','customer LEFT OUTER JOIN filtered orders; count orders per customer, then count customers per order-count bucket.','Preserve customers with zero matching orders. Moving a predicate across an outer join can change the answer.'],
['Promotion effect','lineitem ⋈ part; promotional conditional revenue divided by total revenue.','A single final scalar aggregate still needs distributed partials when several scan tasks run.'],
['Top supplier','revenue view groups lineitems by supplier; a scalar maximum selects top supplier revenue; join supplier attributes.','Capture uses a session temporary view, not persistent CREATE VIEW. The SELECT is unchanged.'],
['Parts/supplier relationship','part ⋈ partsupp; supplier NOT IN a comment-filtered subquery; count distinct supplier per brand/type/size.','Null-aware anti-join can retain broadcast even at threshold −1. DISTINCT adds deduplication/aggregation stages.'],
['Small-quantity revenue','part ⋈ lineitem; correlated average quantity by part filters small-quantity rows; scalar revenue aggregate.','The correlated average is decorrelated into aggregate/join work, not one remote request per lineitem.'],
['Large-volume customers','qualifying order IDs from lineitem GROUP BY order key HAVING quantity above threshold; semi-join plus customer/orders/detail joins; top 100.','Look for ReusedExchange and group stages. A previous executed fixture produced zero rows; an empty answer is not a speedup claim.'],
['Discounted revenue','lineitem ⋈ part with three brand/container/quantity branches; scalar revenue aggregate.','An equi-key hash/merge join can also carry a non-equality residual condition.'],
['Potential part promotion','supplier/nation, partsupp and filtered part; correlated shipped-quantity sum and membership tests.','Semi joins and aggregate branches can be reused. A SQL subquery is not automatically a nested-loop physical join.'],
['Suppliers who kept orders waiting','supplier, orders, nation and multiple lineitem roles; EXISTS plus NOT EXISTS; count late suppliers and top 100.','Anti/semi joins must evaluate supplier inequality residuals correctly; key equality alone is insufficient.'],
['Global sales opportunity','customer phone prefix and balance filter; scalar average over selected customers; anti-membership in orders; group by country code.','Read the scalar subquery section as well as the main plan. Scalar subqueries can have their own row-facing conversion boundary.']
];

export function chapters({section:s,table:t,figure:f,refs:r,code:c,details:d}){
return [
{file:'comet-iceberg-columnar.html',number:27,title:'Comet + Iceberg: from files to columnar operators',intro:'Start with processes, then follow one task through Iceberg planning, Arrow batches, native operators and Spark row boundaries. The plan atlas contains all 22 TPC-H/CometBench-H queries.',sections:[
s('summary','The model in one minute',`${t(['Question','Answer'],[
['Who owns the distributed query?','Spark: Catalyst, stage scheduling, executor placement, retries, broadcast and shuffle transport. Comet does not introduce a separate DataFusion cluster.'],
['What does Comet replace?','Eligible Spark physical operators with native execution backed by Rust, Arrow and DataFusion. Unsupported parts can remain Spark operators.'],
['Where does Rust run?','Inside each executor process through JNI, with task-owned native execution contexts and native runtime threads. Not one Rust pod per operator.'],
['Is Iceberg a server that streams rows?','No. A catalog locates table metadata; snapshots/manifests describe data and delete files. Executor readers access the files.'],
['Does columnar mean zero-copy everywhere?','No. Decoding, filtering, joins, shuffle partitioning, compression, schema adaptation and row conversion can allocate/copy. Arrow FFI avoids some serialization boundaries, not every copy.'],
['What is actually observed here?','88 planning captures on Spark 3.5.3 / Iceberg 1.8.1 / a local Comet 1.1.0-SNAPSHOT JAR. AQE off, 8 shuffle partitions. No result execution or throughput benchmark.']])}
<p><a href="comet-tpch-plan-atlas.html">Open all 22 query plans</a> or <a href="comet-shuffle-joins.html">jump to shuffle and join internals</a>. “TPC dataset” here means the TPC-H-derived CometBench-H SQL in your existing Iceberg demo, not TPC-DS and not an audited TPC benchmark result.</p>${f('deployment')}${r('extensions','exec-rdd','iterator','spark-launch')}`),
s('versions','Two evidence timelines—do not mix them',`<p><strong>Captured plans</strong> describe the installed Spark 3.5.3 runtime and identified JAR bytes. <strong>Source walkthroughs</strong> describe pinned development checkouts: Comet <code>184accac5b9cee6b761a6673c73c263adedef45e</code> and Spark <code>f9358a5587a2d512c5cf08ba4b10d60007c93f6e</code>. The local Comet binary’s exact source tree is not established. Newer source features, flags and fused shuffle internals are not proof that the captured binary implements the same path.</p><p>All source excerpts come from <code>git show &lt;pin&gt;:&lt;file&gt;</code>, excluding dirty local Iceberg changes. Source tests below were inspected, not run. Planning succeeded for all queries and launched no Spark jobs; that does not prove result correctness, spill behavior or multi-executor reliability. The capture is <code>local[2]</code>: one local process, not two executor pods. Cluster diagrams are source-backed illustrations.</p>`),
s('planning','1. Driver: SQL → physical requirements → native fragments',`<ol><li>Spark resolves Iceberg tables and SQL types, simplifies expressions, pushes supported predicates and prunes columns.</li><li>Catalyst rewrites subqueries and chooses join algorithms/build sides using statistics, hints, join type and configuration.</li><li>Physical requirements add exchanges and local sorts when the children do not already provide the required distribution/order. Compatible partitioning can remove a would-be exchange.</li><li>Comet session extensions install rules that recognize eligible scans and operators, serialize native plans, and retain Spark fallbacks where required. Spark’s columnar transition insertion and Comet cleanup rules make representation boundaries explicit.</li><li>Spark turns the resulting RDD dependencies into stages/tasks. A physical node is not a process, a thread, a Spark stage or a network RPC.</li></ol><p>A shuffle partition count of eight means eight logical reduce partitions before adaptive changes—not eight nodes. A task slot executes a partition attempt; multiple operators normally run in that task. A node label’s <code>codegen id</code> identifies a generated-code region, not an executor ID.</p>${r('extensions','spark-strategy','spark-requirements','transitions')}`),
s('scan','2. Iceberg: metadata pruning → exact rows',`${f('iceberg')}<p>The driver-side Iceberg scan resolves a snapshot, schema and projected fields, and plans file tasks. A task includes file/split information, partition constants and relevant delete metadata. Pruning a file using partition or column bounds only proves that some files cannot match; it is not necessarily an exact row-level evaluation of the SQL predicate.</p><p><code>CometIcebergNativeScanExec</code> prepares per-partition serialized scan data. The inspected native <code>IcebergScanExec</code> creates FileIO and an iceberg-rust ArrowReader with projection, delete handling and concurrent file reads. It enters a native runtime context; I/O/CPU work can be asynchronous even though Spark invokes execution from an executor task thread. Returned batches are adapted to the output schema.</p><p>Position deletes identify file positions; equality deletes identify rows by field values. Partition constants, schema evolution and field IDs matter: reading the Parquet columns alone is not equivalent to reading the Iceberg table. The inspected serializer carries delete descriptors and conservatively translated residual predicates; retained Filter nodes enforce remaining predicates. Exact support is version-, type- and delete-format-dependent—do not infer that every Iceberg feature works from one native scan label.</p><p>The captured plans name local metadata files. A real object-store deployment adds remote catalog/metadata and file requests, range reads, credentials and retries. Those are storage calls, not Spark driver RPC per row. Iceberg partition layout also does not automatically establish Spark’s required join hash distribution; the inspected native scan advertises unknown partitioning rather than a blanket storage-partitioned-join guarantee.</p>${r('iceberg-exec','iceberg-serde','iceberg-rust','iceberg-test')}`),
s('native','3. Executor: serialized fragment → RecordBatch stream',`<p><code>CometExecRDD.compute</code> resolves partition inputs, injects partition-specific scan/shuffle data and creates a <code>CometExecIterator</code>. The iterator creates a native plan/context through JNI, polls execution for output batches and releases resources at task completion/end of input. A serialized native subtree can contain scan, filter, projection, join and aggregation together; do not draw a JNI round trip for every row or every logical operator.</p><p>The Rust planner translates protocol operators into DataFusion execution nodes. Filter evaluates a Boolean expression/mask; Project computes selected expressions/columns; aggregate retains keyed accumulator state; joins build/probe or merge; Sort establishes ordering. Operators exchange Arrow RecordBatches, whose arrays carry typed value buffers plus validity and offset buffers where applicable. A vectorized function may still loop over values internally. “Columnar” does not mean every expression uses SIMD.</p><p>Native buffers consume process memory alongside JVM heap, direct buffers, shuffle buffers and concurrent tasks. A larger Arrow batch amortizes calls but increases live memory and sometimes time to first output. Releasing a batch or native plan is an ownership/lifetime operation, not a distributed commit.</p>${r('exec-rdd','iterator','planner-filter','native-joins')}`),
s('conversions','4. ColumnarToRow: where and why?',`${f('boundaries')}${t(['Boundary','What happens','How to recognize it'],[
['Spark vectorized scan → row SQL operators','ColumnarBatch vectors are consumed as InternalRow/UnsafeRow-compatible values; code generation can fuse subsequent row operators.','BatchScan → ColumnarToRow → Filter / Project / joins'],
['Comet fragment → row consumer','CometColumnarToRow exposes native-produced columns to Spark’s row-facing execution/API path.','Often at the root of these captures; also inspect scalar subqueries and fallback islands.'],
['Spark rows → native fragment','CometSparkRowToColumnar converts rows to Arrow-compatible batches.','An interior bridge; not free and not necessarily visible in an all-native example.'],
['Spark non-Arrow columnar → Comet','CometSparkColumnarToColumnar adapts the vector representation.','ColumnarBatch is an interface, not an Arrow memory-layout guarantee.'],
['Native columnar-to-row option','A separate optional converter creates row-format output natively for supported schemas.','In the inspected pin, spark.comet.exec.columnarToRow.native.enabled defaults false. It still outputs rows.']])}<p>Spark’s whole-stage code generation is not “allocate a boxed Java object for every column of every row.” Generated loops can access vectors, keep primitive values and null flags in local variables, and reuse UnsafeRow storage. It is a row-oriented execution contract with substantial optimization. Conversely, Comet keeps eligible compute columnar but can allocate output vectors, materialize hash tables and convert at boundaries.</p><p>Root <code>CometColumnarToRow</code> does not prove every interior operator was columnar. Check the complete tree and exchange mode. Some internal <code>execute()</code> calls introduce conversion in execution even when the display emphasizes a columnar exchange.</p>${r('spark-columnar','comet-c2r','native-c2r','bridge','transitions','jvm-shuffle-input')}`),
s('operators','Operator dictionary: read a plan from leaves upward',`${t(['Spark / Comet node','Consumes → produces','State / distribution / blocking'],[
['BatchScan / CometIcebergNativeScan','Iceberg file tasks → column batches','Pruning, projection, data/deletes; scan task layout is separate from join partitioning.'],
['Filter / CometFilter','Rows/batches → qualifying subset','Usually streaming; null predicate does not pass WHERE. Pushdown and retained filter may both appear.'],
['Project / CometProject','Input attributes → selected/computed attributes','Usually streaming; may reduce shuffle width. Arithmetic/decimal/null semantics still matter.'],
['HashAggregate / CometHashAggregate','Records or partial states → group accumulators/results','Partial, final and distinct stages differ. Look at keys and functions, not just the node name.'],
['Exchange / CometExchange','Upstream partitions → required distribution','Hash, range, round-robin or single partition. This is the distributed boundary.'],
['Sort / CometSort','One input partition → ordered partition','Can buffer/spill; a local sort alone is not global ORDER BY.'],
['BroadcastHashJoin / CometBroadcastHashJoin','Probe partition + broadcast build relation → joined output','Build-side materialization; no need to shuffle the probe solely for this join.'],
['ShuffledHashJoin / CometHashJoin','Co-partitioned inputs → joined output','Per-task build hash table; skew and build-side memory matter.'],
['SortMergeJoin / CometSortMergeJoin','Co-partitioned sorted inputs → joined output','Merge keys, handle duplicate runs and residual condition. Sorting can dominate.'],
['TakeOrderedAndProject / CometTakeOrderedAndProject','Partition candidates → global top K','Distributed candidate selection/merge; the node can hide work below the simple tree.'],
['ReusedExchange','Reference to an existing exchange result','Not a second full recomputation by definition. Reuse is not a separate copy of the source table.'],
['Subquery / reused subquery','Separate scalar/membership computation → value/branch','Read the extra plan sections. Optimizer can decorrelate into joins and aggregates.'],
['ColumnarToRow / CometColumnarToRow','Batches → Spark row contract','Representation boundary, not a shuffle, RPC or durable write.']])}<p>For a detailed node, the captured plan prints inputs, outputs, condition, join type, build side, partition keys and expression IDs. These details are the answer to “what does this operator look like?” The atlas preserves them, not just a simplified screenshot.</p>`),
s('aggregation','Worked examples: Q1 and Q6',`${f('aggregate')}<p><strong>Q1:</strong> each scan task filters lineitems and computes partial sums/counts by return flag and line status. Hash redistribution co-locates the partials for a group; final aggregate merges them. A separate range exchange and sort provide the requested global order. For AVG, merge sum and count (with correct null rules), not the arithmetic mean of task averages. DISTINCT and decimal state can make real plans more complex.</p><p><strong>Q6:</strong> filter → partial revenue sum → SinglePartition exchange → final sum. That exchange merges small partial states rather than shipping every qualifying source row if partial aggregation is effective. A global scalar result requires final coordination even in a columnar engine.</p><p>For an illustrative group, task A has sum 90/count 3 and task B sum 10/count 1. Correct AVG = 100/4 = 25; averaging 30 and 10 would yield 20. This explains why aggregate states, not just result-looking values, cross a partial/final boundary.</p><p><a href="comet-tpch-plan-atlas.html#q1">Q1’s four exact plans</a> · <a href="comet-tpch-plan-atlas.html#q6">Q6’s four exact plans</a></p>`),
s('remember','Presentation mental model',`<p><strong>Spark decides where. Iceberg decides which files and rows belong. Arrow is the batch representation. Comet/DataFusion execute eligible local work. Shuffle moves partitions. A join needs compatible inputs. ColumnarToRow changes representation, not correctness or durability.</strong></p><p>For any diagram, ask five questions: Which process owns this box? What representation crosses this arrow? What distribution/order does the next operator require? What state must fit or spill? What can be recomputed after failure?</p>`)
]},
{file:'comet-shuffle-joins.html',number:28,title:'Shuffle and joins: Spark JVM versus Comet',intro:'Separate the join algorithm, partitioning topology, wire format and implementation language. They are different design decisions, and the physical plan exposes only part of each.',sections:[
s('summary','Four choices that should not be conflated',`${t(['Choice','Examples','Independent question'],[
['Join algorithm','Hash join, sort-merge join, nested-loop fallback','How are matching keys found inside one task?'],
['Distribution','Broadcast build side; shuffle both inputs; reuse existing partitioning','How do matching records reach the same task?'],
['Representation / wire format','UnsafeRows; Arrow batches; compressed shuffle frames','What is buffered and transported?'],
['Execution implementation','JVM generated code; native Rust/DataFusion','Which runtime executes the local operators?']])}<p>A Comet sort-merge join is still a sort-merge join. A Spark hash join is not necessarily a shuffle join. “Native shuffle” does not mean a second native cluster scheduler or bypassing Spark’s network subsystem.</p>${f('join-choice')}${r('spark-strategy','rewrite-join','native-joins')}`),
s('requirements','Why shuffle exists: ownership of matching keys',`<p>Suppose orders contain customer keys <code>[7, 2, 7]</code> and customer contains <code>[2, 7]</code>. For a partitioned equi-join, both sides use compatible expressions/types/hash semantics and the same logical partitioning so all key-7 records reach the same join partition. <code>hash(key) mod N</code> is an intuition, not the exact Spark hash implementation for every data type. Do not substitute an arbitrary Rust hash function.</p><p>Hash partitioning gives <em>co-location</em>, not <em>sorted order</em>. SortMergeJoin additionally requires ascending join-key order on both inputs; EnsureRequirements inserts local sorts where missing. Changing the next join key often requires another exchange. Already-satisfied distribution, broadcast or recognized storage partitioning can avoid one, but table layout alone is insufficient.</p><p>For duplicate key 7, two left rows and three right rows produce six inner-join pairs before a residual condition filters them. A semi-join emits each qualifying left row once; an anti-join emits left rows with no qualifying match. Outer joins also emit preserved unmatched rows with nulls. Normal equality does not match NULL to NULL; null-safe equality and null-aware NOT IN need distinct handling.</p>${r('spark-requirements','native-joins','join-test')}`),
s('spark-shuffle','Path A: ordinary Spark JVM shuffle',`${f('jvm-shuffle')}<ol><li><code>ShuffleExchangeExec</code> prepares a dependency with required partitioning, a row serializer and metrics. Child operators supply rows, possibly after ColumnarToRow.</li><li>Spark’s sort shuffle machinery chooses an appropriate writer (bypass, serialized/unsafe, or general sort path). Rows are assigned reduce-partition IDs, buffered and spilled as needed.</li><li>The writer publishes local map-output data and index information. A map output contains ranges for reduce partitions; a reduce partition can fetch ranges from many map tasks.</li><li>MapStatus carries locations/sizes, not the full dataset, to scheduling/map-output tracking. Reduce tasks fetch the necessary blocks, decode rows and execute downstream operators.</li><li>For SMJ, independent SortExec work establishes join-key order, possibly with spill. “Sort shuffle” refers to organizing shuffle output, not satisfying arbitrary SQL ORDER BY.</li></ol><p>The driver is in the control path, not a central router for every shuffle row. Local fetch can avoid remote transfer; remote fetch uses Spark’s block-transfer client/server and configured limits. Deployment may use an external shuffle service or another supported shuffle system.</p>${r('spark-exchange','spark-manager','spark-fetch')}`),
s('native-shuffle','Path B: Comet native shuffle',`${f('native-shuffle')}<p>In the inspected pin, a <code>CometNativeShuffle</code> exchange can create a thin input RDD carrying a native producer context. <code>CometNativeShuffleWriter</code> puts ShuffleWriter above the eligible native subtree, injects partition inputs and drains its execution. The native side partitions Arrow data, encodes/compresses shuffle frames and spills/writes local output. If the child is not a native subtree, a batch-input bridge is used instead; fusion is not unconditional.</p><p>The local partition writer stages per-partition output and spills when required; finalization produces partition-contiguous output with an offset array. The JVM writer derives partition lengths, commits data/index metadata through Spark’s resolver and returns MapStatus. Publication is attempt output management, not an Iceberg snapshot commit.</p><p>Reducers still discover map locations and fetch blocks through Spark. With direct native shuffle reading enabled and eligible, compressed blocks enter native ShuffleScan. Another path decodes to JVM-visible Arrow-backed ColumnarBatch and feeds a native consumer through Arrow FFI. These are representation/ownership choices within Spark task execution, not an executor-to-executor JNI call.</p>${r('jvm-shuffle-input','native-writer','local-writer','block-reader','shuffle-sink','shuffle-scan','shuffle-test')}`),
s('columnar-shuffle','Path C: Comet JVM columnar shuffle',`${f('jvm-columnar-shuffle')}<p><code>CometColumnarShuffle</code> calls <code>child.execute()</code> in the inspected exchange implementation. If the child is a native columnar node, its row execution wrapper converts output to rows. JVM machinery determines partitions and stores UnsafeRows/pointers; native encoding produces the Arrow-oriented shuffle payload. The reducer uses the Comet block reader and decoder.</p><p>This path can support situations unsuitable for the native producer path, but an extra batch → row → encoded batch route can cost CPU and memory. The physical label <code>CometColumnarExchange</code> must not be explained as proof of a row-free pipeline. The 88 atlas captures use native exchanges where shown; this JVM-shuffle path was source-inspected, not separately benchmarked here.</p><p><code>spark.comet.shuffle.mode</code> supports native/jvm/auto in the inspected source, with auto preferring native when eligible. The experimental force-shuffled-hash-join switch is a separate choice and defaults off. Never change shuffle mode and join algorithm together and attribute the entire timing difference to one.</p>${r('jvm-shuffle-input','shuffle-manager','external-sorter','shuffle-config','rewrite-join')}`),
s('wire','Networking, threads and storage',`${f('network')}${t(['Boundary','Payload / ownership','Not this'],[
['Driver → executor RPC','Task description, serialized execution closure and scheduling control','One RPC per operator or row'],
['Executor task → JNI','Native plan/context, input handles and batch/FFI interfaces','Remote Rust service call'],
['Executor → object store','Metadata/file reads and ranges through configured FileIO','Driver forwarding all Parquet bytes'],
['Map task → local disk','Shuffle data/index, temporary output and spill files','Durable table snapshot or streaming checkpoint'],
['Map output tracking','Block locations and sizes for downstream reads','The shuffle dataset itself'],
['Reducer → block server','Fetch block bytes, with transport flow control/retries','SQL join-key negotiation between all workers'],
['Broadcast exchange → driver → workers','Build-side materialization and broadcast distribution','Same topology as partitioned shuffle']])}<p>An executor JVM has RPC/network machinery and a task pool; several task threads may concurrently own native contexts. Native I/O and execution can also use runtime threads. One physical operator is not one dedicated Java thread. One task does not imply one file, and one exchange does not imply one permanent pod.</p><p>For N maps and R reduce partitions, the logical fan-out can approach N×R block ranges. That is not necessarily N×R physical files: consolidated data/index layouts and batching change file and request counts. Larger R shrinks average partitions but raises metadata, scheduling, fetch and small-block overhead.</p>${r('spark-launch','spark-fetch','block-reader','local-writer')}`),
s('hash','Hash joins: build, probe, duplicates and memory',`${t(['Variant','Distribution','Local execution','Main risk'],[
['Spark BroadcastHashJoinExec','Broadcast build; keep probe partitioning','Broadcast HashedRelation; probe with generated/interpreted row logic','Driver/build materialization, executor memory, timeout and stale size estimates'],
['Spark ShuffledHashJoinExec','Both sides co-partitioned','zipPartitions; build one local HashedRelation per task and probe','One skewed build partition can exhaust memory'],
['CometBroadcastHashJoin','Broadcast serialized Arrow build batches','Native DataFusion hash join consumes task-aligned build/probe input','Broadcast replication plus native build memory; do not assume one globally shared hash table'],
['CometHashJoin','Co-partitioned task inputs','Native HashJoinExec with keyed build/probe and residual JoinFilter','Memory, duplicate expansion, skew and version-specific spill support']])}<p>The inspected Spark SHJ builds its HashedRelation with task memory accounting and registers completion cleanup. BHJ obtains a read-only broadcast relation; duplicate keys can yield several rows for one probe. These are data structures, not external key-value services.</p><p>The Comet Rust planner translates keys, join type and optional condition to DataFusion. Ordinary partitioned joins use Partitioned mode. This means partition-local execution supplied by Spark; DataFusion does not initiate cluster-wide redistribution. Build-right translation may swap native inputs and restore output ordering. Null-aware anti-join uses CollectLeft mode to preserve global null/empty semantics in the inspected implementation.</p><p>Do not promise automatic disk spill for every hash-join implementation/version. A configured memory budget does not guarantee an arbitrarily large build table succeeds. Verify the exact runtime’s join memory behavior and tests before treating hash joins as spill-safe.</p>${r('spark-bhj','spark-shj','native-joins','join-test')}`),
s('merge','Sort-merge joins: what is actually sorted?',`<p>Both inputs must be co-partitioned by compatible equality keys and sorted locally by those keys. The merge scanner advances the smaller key, buffers a matching run when needed and emits valid combinations. With left <code>[2,7a,7b]</code> and right <code>[2,7x,7y,9]</code>, key 2 matches once and key 7 yields four pairs. An inequality residual can reject some pairs without changing the equi-key distribution.</p><p>Spark’s <code>SortMergeJoinExec</code> declares child ordering and uses a partition evaluator/scanner. Its match buffering has memory/spill thresholds. Separate external sorts can spill too. Comet’s planner builds native SortMergeJoinExec with join keys, JoinFilter, sort options and Spark-compatible null behavior; it does not simply rename a hash join.</p><p>SMJ often handles large sortable inputs more predictably through external sorting, but pays shuffle and sort cost. SHJ can remove sorts if a build partition fits. The inspected opt-in Comet RewriteJoin can replace eligible SMJ with hash join and remove sort children, subject to join/build-side limitations. That setting was not enabled for this atlas. A hypothetical SHJ tree must not be substituted for the captured SMJ tree.</p>${r('spark-smj','native-joins','rewrite-join','join-test')}`),
s('broadcast','Broadcast: fewer repartitions, different bottleneck',`${f('broadcast')}<p>Spark’s broadcast exchange collects/builds the relation at the driver and distributes it using Spark broadcast. Comet’s exchange collects serialized columnar batches, checks limits, coalesces/publishes batches and aligns broadcast input with consumer partitions. Native tasks consume this build side to execute the join.</p><p>If build bytes are B and E executors consume them, replicated storage/traffic is roughly proportional to B×E, with actual broadcast distribution and caching changing the transfer pattern. Partitioned shuffle moves both input sides but avoids replicating the entire build relation to every consumer. The driver’s build memory and timeout can fail a broadcast even when probe-side processing is fast.</p><p>The atlas normal mode uses a 10 MiB threshold; it is a choice based on estimated plan size, not a universal measured input-size limit. Threshold −1 disables ordinary size-based automatic broadcast selection, but does not negate semantic special cases or explicit hints. Q16 is the concrete counterexample. Q2 also shows that normal mode need not be all-broadcast.</p>${r('spark-broadcast','comet-broadcast','spark-strategy')}`),
s('q3','Q3: the useful two-join walkthrough',`${f('q3')}<p><strong>Normal capture:</strong> broadcast joins avoid join-input repartitioning for their probe sides. Later aggregation/top-N work can still introduce distributed work; “broadcast joins” is not “no shuffle anywhere.”</p><p><strong>Threshold −1:</strong> customer and orders are hash-partitioned and sorted by customer key for the first join. The intermediate result is then repartitioned/sorted by order key, as is lineitem, for the second join. Four join-input exchanges serve two joins. In this captured shape, order-key partitioning can satisfy grouping requirements, so do not draw an extra aggregate exchange merely because another aggregate node appears.</p><p>Spark JVM shows ColumnarToRow after scans and row SortMergeJoin nodes. Comet shows native scans, CometSort/Exchange/SortMergeJoin and a row-facing root conversion. The topology remains recognizable; the processing representation and local implementation differ.</p><p><a href="comet-tpch-plan-atlas.html#q3">Read all Q3 operator arguments</a>. Q9 is the larger five-join case; Q18 illustrates semi-joins and reuse.</p>`),
s('failure','Failures, retry and durability',`${f('recovery')}${t(['Failure','Expected recovery layer','Limit / caveat'],[
['Task exception or eligible transient read/fetch error','Client retries and/or Spark task retry policy','A deterministic unsupported expression or corrupt file can fail repeatedly.'],
['Executor lost with local shuffle blocks','Spark invalidates unavailable map output and recomputes required stages','External shuffle service or shuffle tracking changes availability; native code does not make local disk replicated.'],
['Native memory exhaustion','Task/query fails; Spark can retry according to policy','Retrying the same skewed partition with the same memory may fail again.'],
['Native crash taking down executor','Spark observes executor loss and reschedules work','JNI shares the process; it is not an isolation boundary.'],
['Driver lost','Application-level restart/recovery policy','An ordinary batch query has no automatic Structured Streaming checkpoint equivalent.'],
['Snapshot data deleted before recomputation','Input cannot be reconstructed from missing files','Retention/expiration policy must preserve files required by active reads and retry.'],
['Task retries while writing an external sink','Sink-specific commit protocol and idempotence','A correct SELECT/shuffle does not establish exactly-once side effects. Iceberg writes need their own commit path.']])}<p>These are batch SELECT plans, not Structured Streaming plans. Shuffle files are disposable intermediate state; Iceberg’s snapshot references and data/delete files are the durable input. Do not label map-output publication a transaction checkpoint or claim native compute changes Iceberg’s durability semantics.</p>${r('spark-failure','native-writer')}`),
s('tradeoffs','Throughput, latency and memory: diagnose the bottleneck',`${t(['Design choice','Can help','Can hurt / inspect'],[
['Project/filter earlier','Less decode, join state and shuffle width','Pushdown must preserve semantics; some predicates remain residual. Inspect scan bytes and rows.'],
['Broadcast a small relation','Avoid large probe repartition/sort','Driver build, replicated memory, size estimate errors; inspect broadcast bytes/time.'],
['Hash instead of merge join','Avoid local sorting','Build memory and skew; inspect maximum partition, not only average.'],
['More shuffle partitions','Smaller task working sets, more parallelism','More tasks/blocks/overhead; eight is only this fixture’s setting.'],
['Larger batches','Amortize JNI/function calls','Higher live memory, latency to first batch and cache pressure.'],
['Compression','Less disk/network traffic','CPU and decompression cost; measure codec and data compressibility.'],
['More concurrent tasks','Utilize CPU and I/O','Each task has live native/JVM/shuffle state; process memory is shared.'],
['AQE','Runtime coalescing, skew handling and join changes where supported','Initial plan differs from final plan; compare equivalent settings and final executed plans.'],
['All-native eligible region','Avoid repeated representation bridges','One unsupported operator can split regions; inspect fallback reasons and transitions.'],
['Spill','Bound some operator working sets','Extra disk read/write, merge passes and long-tail tasks; not all operators spill identically.']])}<p>A rough capacity model is <code>process memory ≈ JVM heap + shared native state + concurrent tasks × per-task native/row/shuffle working set + network/direct buffers</code>. It is a budgeting model, not an exact allocator equation. Throughput is often limited by storage decode, shuffle network/disk, a skewed reducer or output consumption—not by JNI alone.</p><p>Measure scan bytes/rows, shuffle read/write bytes, spill, peak memory, task duration distribution, fetch wait, sort/build time and conversion boundaries. Compare output schema and a deterministic multiset digest before speed. Keep snapshot, query text, AQE, join mode, memory, partitions, warmups and cache state fixed. This guide reports no new speedup.</p>`),
s('remember','The presentation shortcut',`<p><strong>Exchange = where records meet. Sort = in what order they arrive. Hash table = how matches are found. Arrow = how values are laid out. JNI = process-local boundary. Spark = distribution and retry. Iceberg = durable table state.</strong></p><p>When someone asks “is Comet faster because it has native shuffle?”, first show the actual plan: same join algorithm? same build side? same partition count? same scan reader? same conversions? Then explain the measured bottleneck. A different tree is a different execution experiment.</p>`)
]}
];
}
